#ifndef COLOR_H
#define COLOR_H

#include <d3d9.h>
#pragma warning( disable : 4996 )
#include <strsafe.h>
#pragma warning( default : 4996 )

const D3DCOLOR ARGBMASK_NOALFA=0x00FFFFFF;
const D3DCOLOR ARGBMASK_ALFAONLY=0xFF000000;
const D3DCOLOR ARGBMASK_NORED=0xFF00FFFF;
const D3DCOLOR ARGBMASK_REDONLY=0x00FF0000;
const D3DCOLOR ARGBMASK_NOGREEN=0xFFFF00FF;
const D3DCOLOR ARGBMASK_GREENONLY=0x0000FF00;
const D3DCOLOR ARGBMASK_NOBLUE=0xFFFFFF00;
const D3DCOLOR ARGBMASK_BLUEONLY=0x000000FF;

#define DL32COLOR_WHITE 0xFFFFFFFF
#define DL32COLOR_BLACK 0xFF000000

#define DL32COLOR_RED 0xFFFF0000
#define DL32COLOR_GREEN 0xFF00FF00
#define DL32COLOR_BLUE 0xFF0000FF

#define DL32COLOR_ORANGE 0xFFFF8800
#define DL32COLOR_YELLOW 0xFFFFFF00
#define DL32COLOR_PURPLE 0xFF7401DF


D3DCOLOR COLOR_FromARGB(byte A,byte R, byte G, byte B);
D3DCOLOR COLOR_FromRGB(byte R, byte G, byte B);

D3DCOLOR COLOR_GetAlfaColor(D3DCOLOR color);
D3DCOLOR COLOR_GetRedColor(D3DCOLOR color);
D3DCOLOR COLOR_GetGreenColor(D3DCOLOR color);
D3DCOLOR COLOR_GetBlueColor(D3DCOLOR color);

byte COLOR_GetAlfa(D3DCOLOR color);
byte COLOR_GetRed(D3DCOLOR color);
byte COLOR_GetGreen(D3DCOLOR color);
byte COLOR_GetBlue(D3DCOLOR color);

void COLOR_SetAlfa(D3DCOLOR &color,byte A);
void COLOR_SetRed(D3DCOLOR &color,byte R);
void COLOR_SetGreen(D3DCOLOR &color,byte G);
void COLOR_SetBlue(D3DCOLOR &color,byte B);

D3DCOLOR COLOR_Add(D3DCOLOR C1,D3DCOLOR C2);
D3DCOLOR COLOR_Sub(D3DCOLOR C1,D3DCOLOR C2);
D3DCOLOR COLOR_Blend(D3DCOLOR C1,D3DCOLOR C2);

typedef D3DCOLOR dl32Color;
#endif