#define DL32COMPILEMODE_PERFORMANCE 0
#define DL32COMPILEMODE_SECURE 1
#define DL32COMPILEMODE_USERDEFINED 2

#define DL32COMPILEMODE DL32COMPILEMODE_USERDEFINED

#if DL32COMPILEMODE == DL32COMPILEMODE_PERFORMANCE
	#define DL32FLAGS_CHECKOVERFLOW 0
	#define DL32FLAGS_CHECKARRAYINDEXES 0
	#define DL32FLAGS_CHECKMATRIXOPERATIONS 0
	#define DL32FLAGS_MATRIXASIGNCOPYREF 1
#elif DL32COMPILEMODE == DL32COMPILEMODE_SECURE
	#define DL32FLAGS_CHECKOVERFLOW 1
	#define DL32FLAGS_CHECKARRAYINDEXES 1
	#define DL32FLAGS_CHECKMATRIXOPERATIONS 1
	#define DL32FLAGS_MATRIXASIGNCOPYREF 0
#else
	//#error DL32COMPILEMODE == DL32COMPILEMODE_USERDEFINED: No DL32FLAGS defined !!!
	#define DL32FLAGS_CHECKOVERFLOW 1
	#define DL32FLAGS_CHECKARRAYINDEXES 1
	#define DL32FLAGS_CHECKMATRIXOPERATIONS 1
	#define DL32FLAGS_MATRIXASIGNCOPYREF 1
#endif

#define DL32NULLPOINTER 0
#define NULL DL32NULLPOINTER
#define DL32RETURN_ERROR(x) x<0
#define DL32RETURN_ERRORCODE -1

#define DL32DEBUG_DEBUGTEST 2