//CONFIGURACIÓN DE TESTS:
/////////////////////////

#include "dl32Config.h"

#define DL32TEST_NOTEST -1

#define DL32TEST_GENERAL_STRESS 0
#define DL32TEST_GENERAL_MATRIX 1
#define DL32TEST_GENERAL_ECUATIONSYSTEM 2

#define DL32TEST_MANDELBROTFRACTAL_SIMPLETEST 3

#define DL32TEST_PARTICLEENGINE_SIMPLETEST 4

#define DL32TEST_LAURA_PONG_PSEUDOPLAYABLE 5

#define DL32TEST_POLYLINE_SIMPLETEST 6

#define DL32TEST_ISOMETRICENGINE_ENGINETEST 7

#define DL32TEST_REFACTORING_EVENTSSYSTEM 8



#define DL32TESTS_CURRENTTEST DL32TEST_REFACTORING_EVENTSSYSTEM 


#define DL32DEBUG_SPLINE_PROMPTINTERVALDATA NO
#define DL32DEBUG_GENERAL_PROMPTUNHANDLEDEXCEPTIONS YES